Repository HOP-3-Duluu/BingChilling, pull requests merged in 2023-05, with the labels that each got.

#27 25 location banner front end
  BingParking/package-lock.json
  BingParking/package.json
  BingParking/src/components/tempo/Banner.tsx
  BingParking/src/components/tempo/index.ts
  BingParking/src/navigations/stack/Stack.tsx
  BingParking/src/screens/Home.tsx
  bing-back-end/.build/src/users/createUser.js
  bing-back-end/.build/src/users/createUser.js.map
  bing-back-end/.build/src/utils/index.js
  bing-back-end/.build/src/utils/index.js.map
  bing-back-end/.gitignore
  bing-back-end/package-lock.json
  bing-back-end/package.json
  bing-back-end/serverless.yml
  bing-back-end/src/bing.ts
  bing-back-end/src/main/getLocations.ts
  bing-back-end/src/main/notifs.ts
  bing-back-end/src/main/parkings.ts
  bing-back-end/src/main/setLocation.ts
  bing-back-end/src/sqs/notifsqs.ts
  bing-back-end/src/users/createUser.ts
  bing-back-end/src/users/deleteUser.ts
  bing-back-end/src/users/getUser.ts
  bing-back-end/src/users/updateUser.ts
  bing-back-end/src/utils/index.ts
Labels: good first issue

#30 Forgot password Front End -> Bilguun
  BingParking/ios/BingParking/Info.plist
  BingParking/ios/Podfile.lock
  BingParking/package-lock.json
  BingParking/package.json
  BingParking/src/assets/forgotPass.png
  BingParking/src/assets/verify.jpg
  BingParking/src/components/Header.tsx
  BingParking/src/navigations/stack/Stack.tsx
  BingParking/src/screens/Home.tsx
  BingParking/src/screens/forgotpass/cnp.tsx
  BingParking/src/screens/forgotpass/fp.tsx
  BingParking/src/screens/forgotpass/index.tsx
  BingParking/src/screens/forgotpass/verify.tsx
Labels: good first issue

#31 Bek ForgotPass -> Front-End
  BingParking/ios/Podfile.lock
  BingParking/src/components/forgotpass/cnp.tsx
  BingParking/src/components/forgotpass/fp.tsx
  BingParking/src/components/forgotpass/verify.tsx
Labels: duplicate

#33 25 location banner front end
  BingParking/App.tsx
  BingParking/package-lock.json
  BingParking/package.json
  BingParking/src/components/notif/Notif.tsx
  BingParking/src/components/tempo/Banner.tsx
  BingParking/src/contexts/locationCont.tsx
Labels: duplicate

#38 Bilguun has done coding front-end of many stuffs
  BingParking/src/components/auth/login.tsx
  BingParking/src/components/auth/signup.tsx
  BingParking/src/components/auth/starter.tsx
  BingParking/src/components/baseScreen/BaseFour.tsx
  BingParking/src/components/baseScreen/BaseOne.tsx
  BingParking/src/components/baseScreen/BaseThree.tsx
  BingParking/src/components/baseScreen/BaseTwo.tsx
  BingParking/src/components/forgotpass/cnp.tsx
Labels: documentation, duplicate

#40 22 location search component
  BingParking/src/components/baseScreen/BaseFour.tsx
  BingParking/src/components/baseScreen/BaseOne.tsx
  BingParking/src/components/baseScreen/BaseThree.tsx
  BingParking/src/components/baseScreen/BaseTwo.tsx
  BingParking/src/components/owner/ParkAdd.tsx
  BingParking/src/components/search/index.ts
  BingParking/src/components/search/searchMain.tsx
  BingParking/src/components/tempo/Banner.tsx
  BingParking/src/contexts/userCont.tsx
  BingParking/src/navigations/stack/Stack.tsx
  BingParking/src/screens/Home.tsx
  BingParking/src/utils/aws.ts
  bing-back-end/package-lock.json
Labels: good first issue

#42 Bek has pushed -> #41
  BingParking/babel.config.js
  BingParking/ios/BingParking/Info.plist
  BingParking/ios/Podfile.lock
  BingParking/package-lock.json
  BingParking/package.json
  BingParking/src/components/owner/ParkAdd.tsx
  BingParking/src/contexts/userCont.tsx
  BingParking/src/screens/Home.tsx
Labels: good first issue

#43 LastPR-#1
  BingParking/ios/Podfile.lock
  BingParking/src/components/forgotpass/beforeVerify.tsx
  BingParking/src/components/forgotpass/fp.tsx
  BingParking/src/components/forgotpass/verifygmail.tsx
  BingParking/src/navigations/stack/Stack.tsx
Labels: duplicate, good first issue
